# Generated by Django 3.0.3 on 2020-08-22 02:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0005_auto_20200822_0214'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tasklog',
            name='create_date',
        ),
        migrations.RemoveField(
            model_name='tasklog',
            name='update_date',
        ),
        migrations.AlterField(
            model_name='tasklog',
            name='end_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
