# Generated by Django 3.0.3 on 2020-08-04 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='estimate_time',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='task',
            name='priority',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='task',
            name='status',
            field=models.CharField(default='pending', max_length=150),
        ),
        migrations.AddField(
            model_name='task',
            name='time',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
