# Generated by Django 3.0.3 on 2020-08-04 00:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0002_auto_20200804_0024'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='estimate_time',
            new_name='estimated_time',
        ),
    ]
