# Generated by Django 3.0.3 on 2020-08-22 02:14

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0004_auto_20200817_1527'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='description',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.CreateModel(
            name='TaskLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(default='running', max_length=250)),
                ('start_date', models.DateTimeField(default=datetime.datetime.now)),
                ('end_date', models.DateTimeField(null=True)),
                ('create_date', models.DateTimeField(default=datetime.datetime.now)),
                ('update_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapi.Task')),
            ],
        ),
    ]
