# Generated by Django 3.0.3 on 2020-08-22 02:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0006_auto_20200822_0216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasklog',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
